/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/images": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.images.id"];
          template_number?: parameters["rowFilter.images.template_number"];
          scene_number?: parameters["rowFilter.images.scene_number"];
          image_number?: parameters["rowFilter.images.image_number"];
          image_url?: parameters["rowFilter.images.image_url"];
          created_at?: parameters["rowFilter.images.created_at"];
          user_id?: parameters["rowFilter.images.user_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["images"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** images */
          images?: definitions["images"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.images.id"];
          template_number?: parameters["rowFilter.images.template_number"];
          scene_number?: parameters["rowFilter.images.scene_number"];
          image_number?: parameters["rowFilter.images.image_number"];
          image_url?: parameters["rowFilter.images.image_url"];
          created_at?: parameters["rowFilter.images.created_at"];
          user_id?: parameters["rowFilter.images.user_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.images.id"];
          template_number?: parameters["rowFilter.images.template_number"];
          scene_number?: parameters["rowFilter.images.scene_number"];
          image_number?: parameters["rowFilter.images.image_number"];
          image_url?: parameters["rowFilter.images.image_url"];
          created_at?: parameters["rowFilter.images.created_at"];
          user_id?: parameters["rowFilter.images.user_id"];
        };
        body: {
          /** images */
          images?: definitions["images"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  images: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: smallint */
    template_number: number;
    /** Format: smallint */
    scene_number: number;
    /** Format: smallint */
    image_number: number;
    /** Format: text */
    image_url: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at: string;
    /**
     * Format: uuid
     * @default extensions.uuid_generate_v4()
     */
    user_id: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description images */
  "body.images": definitions["images"];
  /** Format: bigint */
  "rowFilter.images.id": string;
  /** Format: smallint */
  "rowFilter.images.template_number": string;
  /** Format: smallint */
  "rowFilter.images.scene_number": string;
  /** Format: smallint */
  "rowFilter.images.image_number": string;
  /** Format: text */
  "rowFilter.images.image_url": string;
  /** Format: timestamp with time zone */
  "rowFilter.images.created_at": string;
  /** Format: uuid */
  "rowFilter.images.user_id": string;
}

export interface operations {}

export interface external {}
